import React from 'react';

const Terms = ({ setAgreeTerms }) => {

  const handleAccept = () => {
    setAgreeTerms(true);
  };
  
  return (
    <div className="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabIndex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div className="modal-dialog modal-xl modal-dialog-scrollable">
        <div className="modal-content"  style={{ backgroundColor: 'rgb(19, 19, 72)' }}>
          <div className="modal-header">
            <h1 className="modal-title fs-5" id="staticBackdropLabel">Terminos y Condiciones:</h1>
            <button type="button" className="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div className="modal-body">
            <p>Los siguientes constituyen los “Términos y Condiciones” que rigen la utilización del Sitio lilianagamesstore.onrender.com (en adelante el “Sitio”) por parte de nuestros Clientes  (en adelante denominados, indistintamente, los “Clientes” o “Usuarios”).</p>
            <p>Los términos y condiciones deben entenderse expuestos con el propósito de asegurar que los consumidores en general sean adecuadamente protegidos y puedan sentirse seguros al realizar transacciones vía Internet y con la intención de ser una clara guía sobre las características fundamentales que debe contener la información que se difunda por este medio, así como de las prácticas comerciales equitativas que los empresarios deben realizar y que los consumidores tienen derecho a recibir en el contexto del comercio electrónico, proporcionándoles información precisa, suficiente y fácilmente accesible, que describa los bienes o servicios ofrecidos así como los costos asociados a las operaciones, de manera que permita a los consumidores tomar una decisión informada antes de participar en la transacción, manteniendo un adecuado registro de dicha información.</p>
            <p>LilianaGameStore.com, garantiza a los Usuarios del Sitio condiciones de atención, trato digno, equitativo y no discriminatorio y mediante estos términos y condiciones cumple con el deber de suministrarles la debida información, de modo cierto y detallado, en relación con todos los datos necesarios para el acceso y uso del Sitio, los eventuales riesgos derivables de su empleo, las características esenciales de los bienes y servicios que provee y las condiciones de su comercialización. Más allá de la sincera decisión de LilianaGameStore.com de hacerlo con la suficiente claridad que facilite su adecuada comprensión por parte de los Usuarios, éstos no están obligados a aceptarlos, no debiendo hacerlo si no los comprenden, sin perjuicio que, de aceptarlos, en cualquier momento, podrán ejercer la facultad que le asiste de revocar su decisión.</p>
            <p>Cada vez que los Clientes deseen utilizar el Sitio, deberán verificar los términos y condiciones vigentes en ese momento, advertidos que éstos pueden haber sido modificados desde la última vez que accedieron, absteniéndose de usarlo de no estar de acuerdo con cualquiera de los mismos, en el entendimiento que, de usar el Sitio, habrá de interpretarse a esta conducta como un signo inequívoco y revelador de su conformidad y aceptación de todos los términos y condiciones, y su consecuente obligación de respetarlos, ajustándose a los mismos.</p>
            <p>LilianaGameStore.com, en su carácter de propietario y operador del Sitio se reserva con carácter exclusivo el derecho a realizar modificaciones en el mismo, así como el de interrumpir el servicio ofrecido, en forma transitoria o definitiva. Toda vez que proceda a realizar modificaciones de los términos y condiciones, las que se realicen aparecerán publicadas en el Sitio, debiendo los Usuarios asegurarse que son la versión vigente, al momento del inicio de cada sesión.</p>
            <p>Asimismo, LilianaGameStore.com podrá cancelar sin previo aviso la condición de Usuarios, y en consecuencia denegar el acceso al Sitio o a comprar por esta vía, en caso que los Usuarios no cumplieran con cualesquiera de los términos y condiciones del Sitio, pudiendo hacerlo también en relación con aquéllos visitantes del Sitio aún cuando éstos no se encuentren registrados (“Usuarios Registrados”).</p>
            <p>Los Usuarios, al utilizar el Sitio, deben tener presente que estarán aceptando todos y cada uno de los términos y condiciones vigentes en ese momento, los que pasarán a ser considerados partes del contrato que los mantendrá vinculados a LilianaGameStore.com, hasta su resolución. A los Usuarios le asistirá el derecho a resolver la relación contractual, en cualquier momento, siempre que lo hagan para el futuro evitando el uso del Sitio y siendo Usuarios Registrados, renunciando a su inscripción, siguiendo el procedimiento especialmente previsto con esa finalidad. LilianaGameStore.com también podrá resolver el contrato en cualquier momento siendo válida la notificación de tal decisión a los domicilios reales o electrónicos que los Usuarios tuvieran declarados en el Sitio.</p>
            <p>Los Usuarios, al aceptar los términos y condiciones del Sitio, estarán asumiendo el compromiso de tomar a su cargo cualquier responsabilidad contractual o extracontractual que sean consecuencias directas o indirectas de sus actos, siendo su obligación mantener indemne a LilianaGameStore.com, en relación con cualquier reclamo que pueda razonablemente asociarse a un uso indebido del Sitio por su parte, incluyendo, sin desconsideración de otros, cualquier comentario que aparezca publicado en cualquier medio en relación con los servicios a los que se accede a través del uso del Sitio, con manifiesta o velada intención perjudicial, que pudiera serle atribuida.</p>
            <p>Los títulos de los términos y condiciones deberán tener presente los Usuarios que sólo son empleados con fines de referencia a las disposiciones que se describen debajo de cada uno de éstos. De ser cualquiera de éstas consideradas inaplicables, cualquiera fuese la razón que así lo determine, LilianaGameStore.com se reserva el derecho de reformularlas en la medida que sea necesaria para hacerlas exigibles, no pudiendo interpretarse su falta de acción ante cualquier incumplimiento de los términos y condiciones que rigen la utilización del Sitio como una renuncia ni una limitación a sus derechos.</p>
            <p>1- Usuarios que pueden utilizar el Sitio LilianaGameStore.com. El Sitio sólo puede ser utilizado por personas humanas que tengan capacidad legal para contratar y en el caso de las personas jurídicas, por quién tenga facultad para obligarlas. No podrán utilizarlo las personas incapaces de ejercicio, los declarados incapaces o restringidos en su capacidad por sentencia inscripta en el Registro de Estado Civil y Capacidad de las Personas y los Usuarios cuya registración para el uso del Sitio se les haya cancelado o rechazado. El uso del Sitio por parte de quiénes carecieran de capacidad legal para hacerlo será responsabilidad de los padres, tutores, curadores o de quiénes los representen legalmente.</p>
            <p>2- Registración como usuario de LilianaGameStore.com. La registración en el Sitio por parte de los Usuarios es voluntaria y gratuita e importa la obligación de completar los datos que le fueren solicitados, de modo exacto y preciso, así como el compromiso de actualizarlos, cuando corresponda, garantizando la veracidad, exactitud, vigencia y autenticidad de los que declarasen. Jamás LilianaGameStore.com habrá de solicitar a los Usuarios datos que puedan ser asociados con su origen racial y étnico, opiniones políticas, convicciones religiosas, filosóficas o morales, afiliación sindical y/o política e información referente a su salud o a su vida sexual.</p>
            <p>Al registrarse en este Sitio, LilianaGameStore.com solicitará a los Usuarios el suministro de toda la información necesaria para brindar un mejor servicio a los Clientes (Vgr.: apellidos y nombres completos, fecha de nacimiento, domicilios real, legal y/o laboral, números telefónicos y correos electrónicos de contacto, y/o cualquier otro dato cuyo registro los Usuario voluntariamente proporcionen interesados en su registración), siendo los datos registrados por LilianaGameStore.com incluidos en archivos automatizados, procesados bajo normas de estricta confidencialidad y protección de datos, con el objeto, -aun cuando las medidas de seguridad en Internet no sean inviolables-, de arbitrar todos los mecanismos de seguridad informática a su alcance, en función de evitar el mal uso, alteración, acceso no autorizado y/o robo de los datos suministrados por los Usuarios.</p>
            <p>Al registrarse en el Sitio los Usuarios, estarán aceptando que los datos que proporcionen, podrán ser utilizados por LilianaGameStore.com con fines operativos del sistema de comercio electrónico en este Sitio e incluso para hacerles llegar por distintos medios ofertas de productos o servicios, anuncios de promociones y publicidad.</p>
            <p>Los servicios de emisión de información a los Usuarios vía correo electrónico, correo postal, mensaje de texto (SMS) y whatsapp, cuentan con la autorización de los Usuario, que en caso de no desear recibir este tipo de información podrá solicitarlo a LilianaGameStore.com por medio fehaciente, o telefónicamente al Centro de Atención al Cliente al 0800-345-93315 o por email a contacto@lilianagamestore.com</p>
            <p></p>
            <p>3- Utilización de la contraseña de usuario. Cada uno de los Usuarios al registrarse dispondrán de un nombre y una contraseña de acceso segura y confidencial, pudiendo reemplazarla, cuando así lo deseen, para lo cual sólo deberán seguir el procedimiento establecido para tal fin. LilianaGameStore.com se reserva el derecho de rechazar cualquier solicitud de registración así como el de cancelar una registración previamente aceptada, no estando obligado a comunicar o exponer las razones de su decisión y sin que ello genere algún derecho a indemnización o resarcimiento.</p>
            <p>Los Usuarios, al registrase, estarán asumiendo el compromiso de no divulgar la contraseña (clave de acceso) a terceros. Ésta clave les permitirá efectuar compras de los productos y servicios que aparezcan en el Sitio así como también obtener información. Cada una de las claves son de exclusivo uso personal, siendo sus Usuarios los únicos responsables de mantener la confidencialidad de su contraseña, responsabilizándose de todas las actividades que se registren en sus respectivas cuentas en el Sitio, asumiendo la obligación de notificar de inmediato y por medio idóneo y fehaciente a LilianaGameStore.com cualquier uso no autorizado de su contraseña o cuenta de que tenga conocimiento, a través del Sitio, especificando y dando  detalle de toda la información que al respecto posea.</p>
            <p></p>
            <p>4- Confidencialidad de datos. El Sitio tiene una estricta política de privacidad y protección de los datos generados por la actividad en línea de sus Usuarios y la información recolectada será utilizada por LilianaGameStore.com con el único propósito de mejorar las ofertas de bienes y servicios a sus Clientes, estando LilianaGameStore.com autorizado a analizar la información relacionada con sus Clientes como grupo y, en base al análisis que pueda hacer, ofrecer, individualmente o en conjunto con terceros, los bienes y servicios que comercialice.</p>
            <p>LilianaGameStore.com ha cumplido los requisitos exigidos por la ley Nº 25.326 de Protección de Datos Personales y tiene registradas sus Bases de Datos ante la Dirección Nacional de Protección de Datos Personales. Al declarar los Usuarios sus datos personales en el Sitio, deben saber que estarán prestando el consentimiento previsto por la citada disposición legal, incluyendo la posibilidad de sucesión conforme lo normado por el artículo 11 de la misma, en virtud de lo cual, salvo en aquéllos casos en que los Usuarios hayan procedido a revocar sus respectivos consentimientos, los datos personales que hayan sido registrados, podrán ser cedidos a empresas vinculadas a LilianaGameStore.com, con el único fin de hacerles llegar, por distintos medios, ofertas de productos o servicios, acciones promocionales de marketing o publicidad.</p>
            <p>LilianaGameStore.com se encuentra inscripto en el Registro Nacional de la Dirección Nacional de Protección de Datos Personales, dependiente del Ministerio de Justicia y Derechos Humanos y de acuerdo con lo dispuesto por el artículo 14 de la ley Nº 25.326 de Protección de Datos Personales se informa a los Usuarios que el titular de los datos, previa acreditación de su identidad, tiene derecho a solicitar y obtener información de sus datos personales incluidos en los bancos de datos públicos, o privados destinados a proveer informes, pudiendo ejercer este derecho en forma gratuita a intervalos no inferiores a seis meses, salvo que se acredite un interés legítimo al efecto. La Dirección Nacional de Datos de Protección de Datos Personales tiene la atribución de atender las denuncias y reclamos que se interpongan en relación con el incumplimiento de las normas sobre protección de datos personales (para más información podrá consultarse en la dirección: http://www.jus.gov.ar/dnpdp).</p>
            <p>Los Usuarios tienen derecho a que sus datos sean rectificados y hasta suprimidos así como también la obligación de actualizarlos cuando corresponda; por medio de nota o presentación escrita con firma certificada, medio postal o telegráfico y/o carta documento acreditando fehacientemente su identidad, debiendo LilianaGameStore.com proceder a la rectificación, supresión o actualización de los datos personales de los Usuarios, según corresponda, realizando las operaciones necesarias para tal fin. En el supuesto de cesión, o transferencia de datos, LilianaGameStore.com deberá notificar toda rectificación, supresión o actualización al cesionario inmediatamente de efectuado el tratamiento del dato. LilianaGameStore.com habrá de entenderse relevado del deber de secreto mediando resolución judicial y cuando medien razones fundadas relativas a la seguridad pública, la defensa nacional o la salud pública.</p>
            <p></p>
            <p>5- Compra de productos y servicios en LilianaGameStore.com. En el Sitio los Usuarios podrán obtener una clara y precisa información acerca de las características de los productos y servicios ofrecidos, su disponibilidad, así como las condiciones de contratación en cuanto a los precios, la moneda y las modalidades de pagos, las condiciones de financiación, la responsabilidad por la entrega, el proceso general de compra, que los Usuarios deberán leer con la debida atención antes de confirmar cualquier transacción.</p>
            <p>Al optar por realizar sus compras a través del Sitio, los Usuarios deberán tener presente que, eventualmente, alguna de éstas pueden llegar a tener que ser anuladas, toda vez que en razón del tiempo que llevan las tareas de actualización del sistema, desde la compra hasta su aceptación, puede que el stock que estaba disponible se haya agotado.</p>
            <p>Asimismo, los Usuarios deberán estar prevenidos que las compras también pueden que sean canceladas debido a limitaciones en las cantidades disponibles; falta de autorización a la operación por parte de la entidad emisora o administradora de su tarjeta de crédito; inexactitudes o errores en el producto o información; o problemas identificados por el área de prevención de fraudes;  reservándose LilianaGameStore.com el derecho, en tanto mediaran razones que así lo justifiquen, de limitar la cantidad de productos o servicios comprados por la misma cuenta o la misma tarjeta de crédito o la misma dirección de facturación y/o de entrega.</p>
            <p>En todos los casos que deban realizarse modificaciones o cancelaciones parciales de sus compras, les asistirá a los Clientes el derecho a cancelar la totalidad de las operaciones que hayan realizado.</p>
            <p>Para realizar compras a través del Sitio, los Usuarios pueden recorrerlo, y luego de su selección, cargar virtualmente al carrito los productos y servicios que deseen adquirir, indicando en cada caso la cantidad requerida.</p>
            <p>LilianaGameStore.com puede necesitar información adicional o realizar verificaciones antes de aceptar cualquier compra. Si se cancela una compra o si se necesita información adicional, LilianaGameStore.com habrá de tomar contacto con los Clientes que corresponda.</p>
            <p>Una vez de aceptada la compra por los Clientes, les llegará un e-mail a sus respectivas casillas de correo con el número y los detalles de las mismas, confirmándose el éxito de la operación. En caso que ello no ocurriese, dentro de las cuarenta y ocho (48) horas siguientes, para su debida información, los Clientes deberán comunicarse telefónicamente al Centro de Atención al Cliente al 0800-345-93315 o por email a contacto@lilianagamestore.com.</p>
            <p>Los comprobantes a emitirse por las compras de productos y servicios que realicen los Clientes le serán enviados a los Clientes por vía electrónica a la dirección que indique cada uno en el momento de la compra, dentro de un plazo estimado de quince (15) días hábiles posteriores a la misma, salvo que medien razones inevitables, que imposibiliten su entrega en el plazo predispuesto, ajenas a la responsabilidad de LilianaGameStore.com.</p>
            <p></p>
            <p>6- Medios de pagos en LilianaGameStore.com. Los medios de pago habilitados para realizar compras en LilianaGameStore.com son: Pago mis cuentas, Tarjetas de Crédito emitidas en Argentina o en el extranjero y MercadoPago,  entre los cuales los Usuarios del Sitio podrán elegir una vez registrados, informándose  a su vez acerca de los planes disponibles de cada entidad y prestadora autorizadas. LilianaGameStore.com sólo emite factura TIPO B.</p>
            <p>Estos medios de pago pueden estar disponibles o no, dependiendo del tipo de direcciones de envío y facturación.</p>
            <p>LilianaGameStore.com no será responsable por los reintegros que deban efectuar los Bancos emisores de tarjetas de crédito respecto de las promociones vigentes, siendo dichas entidades emisoras las únicas responsables de efectivizar en tiempo y forma el reintegro correspondiente. LilianaGameStore.com no recolecta ni almacena datos de las tarjetas de crédito de los Clientes, ni define el resultado de la operación, siendo esto responsabilidad exclusiva de la respectiva entidad bancaria emisora.</p>
            <p></p>
            <p>7- Servicio de Envío a domicilio. La Empresa se reserva el derecho de definir el medio de entrega de los productos, acorde la disponibilidad del servicio. En el caso de que la entrega se realice con logística propia, el servicio de envío a domicilio tendrá el siguiente alcance:</p>
            <p>La Empresa se compromete a hacer la entrega en domicilio:</p>
            <p>· Con embalaje adecuado y en condiciones.</p>
            <p>· En el primer ambiente techado.</p>
            <p>· Hasta el 1er piso por escalera, en caso de departamento, si la estructura edilicia lo permite.</p>
            <p>· Sin ticket/factura, al titular o persona que éste autorice, acreditando identidad.</p>
            <p></p>
            <p>Está prohibido al personal de reparto:</p>
            <p>· Ingresar productos por ventanas y balcones.</p>
            <p>· Desembalar, armar o instalar.</p>
            <p>· Entregar a un menor de edad.</p>
            <p>· Retirar productos, no respaldados por una operación de cambio.</p>
            <p></p>
            <p>Estas condiciones podrán ser modificadas por la Empresa. En el caso de que la entrega se realice con logística de Oca ó Andreani, el servicio de envío a domicilio tendrá el siguiente alcance:</p>
            <p>. Entrega en el domicilio consignado en factura.</p>
            <p>. Con embalaje adecuado y en condiciones</p>
            <p>. La entrega se realiza en el 1er acceso del domicilio</p>
            <p></p>
            <p>El costo del servicio de envío depende de las dimensiones del o de los productos que se adquieran y de la dirección de entrega de los mismos. Acerca del precio los Usuario habrán de ser debidamente informados en oportunidad de realizar el proceso de la compra, previamente a su confirmación. Dicho costo será sumado al de los productos y servicios adquiridos detallados en la correspondiente factura. La confirmación del pedido y el pago realizado on line, implicarán la aceptación por parte de los Usuarios del costo del servicio informado y consecuentemente también el monto total de la correspondiente factura que recibirá en el e-mail registrado en el pedido.</p>
            <p>Por logística interna, para que los Usuarios puedan disfrutar de los productos lo más rápido posible, sus compras pueden ser enviadas en forma particionada en más de una entrega.</p>
            <p>El plazo de entrega de la compra, depende de la dirección de entrega y de la ubicación del depósito desde donde se envían los productos. En Ciudad Autónoma de Buenos Aires y el Gran Buenos Aires la entrega se realiza dentro del plazo estimado de cuarenta y ocho (48) horas hábiles y en el interior del país dentro del plazo estimado de siete (7) días hábiles. El tiempo estimado de entrega debe computarse a partir de la recepción del correspondiente e-mail que cada uno de los Usuarios reciba en su casilla de correo informando el envío de su compra.</p>
            <p>Los Clientes podrán designar una persona autorizada a recibir la mercadería y/o servicio adquirido en el domicilio de entrega indicado. En todos los casos, para que la mercadería y/o servicio sea entregado, la persona autorizada deberá exhibir su DNI.</p>
            <p>La firma del remito y/o la del comprobante de pago implicará declaración de conformidad con la mercadería entregada, sin perjuicio de los derechos que le pudieren corresponder en caso de que la misma resultara por algún motivo defectuosa.</p>
            <p>En caso de que en el día de entrega no se encuentre en el domicilio a la persona habilitado para la recepción, se dejará un aviso y para volver a coordinar otra fecha de entrega, sin que se devengue por ello ningún cargo adicional para los Clientes, éstos deberán comunicarse telefónicamente al Centro de Atención al Cliente al 0800-345-93315 o por la ventana de Contacto de la web Liliana GameStore.</p>
            <p></p>
            <p>8- Servicio RETIRO YO (comprá online y retiro en sucursal): De elegir los Clientes esta opción bastará con que seleccionen:</p>
            <p>a. Los productos y servicios que deseen comprar y opten por el servicio RETIRO YO (indicativo de su voluntad de retirarlos en la sucursal elegida)</p>
            <p>b. Indicando la sucursal donde habrán de retirarlos.</p>
            <p>Hecha esta elección a los Clientes se les enviarán dos correos.</p>
            <p>* Confirmación de compra: confirmando la operación.</p>
            <p>* Confirmación de retiro: Una vez recibido el e-mail de confirmación de su compra y habilitación para retirar el/los producto/s y servicio/s adquirido/s, podrá dirigirse, dentro de los diez (10) días corridos, o el día hábil inmediato siguiente, a la sucursal que haya seleccionado, con el comprobante de la compra efectuada impreso o exhibido en su dispositivo móvil, y retirar su pedido. Vencido el plazo durante el cual habrán de estar a disposición de los clientes los productos adquiridos, LilianaGameStore.com quedará habilitada a cancelar la operación. Cuando se presente en la sucursal, deberá presentar; DNI y tarjeta con la que realizó el pago (en formato físico o digital), excepto que la compra haya sido realizada mediante Mercado Pago o Pago mis cuentas. En caso que la persona que retira el producto no es dicho titular, deberá presentar la imagen del DNI del titular del medio de pago más una imagen del frente de la tarjeta con la que se realizó la compra (digital o impresa) y su DNI para verificar que sea mayor de 18 años. Si la compra es realizada a través de Mercado Pago, la entrega se hará efectiva sólo al titular del medio de pago, sin excepción.</p>
            <p></p>
            <p>9- Precios de productos y promociones. Los precios y promociones que se ofrecen en LilianaGameStore.com, son exclusivos para el Sitio, y no son aplicables a otros canales de comercialización como ser: sucursales, ventas telefónicas, catálogos. La validez de las promociones, depende de la fecha de vigencia de las mismas o de la disponibilidad del stock informado. Las promociones no son acumulables entre sí, salvo que se exprese lo contrario en el Sitio. En el caso que un producto o servicio figure en las listas del Sitio a un precio incorrecto debido a un error, LilianaGameStore.com tendrá el derecho, de corregir la orden facturando el precio vigente al momento del armado del pedido en la tienda o bien, de anular el pedido reintegrando a los Usuarios los importes que hayan abonados. En este caso, se dará aviso del error a los Usuarios, y con él la posibilidad de cancelar o modificar la compra del producto facturado u ofrecido de forma incorrecta. De lo que aquí se trata, es de advertir a los Usuarios que, por razones de buena fe, cuando por error se ofreciera vender a través del Sitio un producto por una suma notoriamente más baja comparativamente con el valor de mercado de un producto similar al publicitado, éste se entenderá que reviste la naturaleza de un "error obstativo", “reconocible” en los términos del art. 266 del Código Civil y Comercial de la Nación, quedando facultado LilianaGameStore.com a proceder conforme se establece en este punto.</p>
            <p>Los precios publicados en lilianagamesstore.onrender.com pueden diferir dependiendo de la zona geográfica de donde se realiza la conexión al sitio, el precio final del producto será correspondiente a la zona geográfica en la que esté ubicado el domicilio informado por usted a los fines de la confección de la factura correspondiente.</p>
            <p></p>
            <p>10- Imágenes y descripciones de productos. Las imágenes de los productos y sus descripciones son ilustrativas y no contractuales. Aún cuando la ilustración pretende ser lo más precisa posible, los Usuarios no pueden inadvertir que las descripciones de los productos u otros contenidos de este Sitio pueden que no sean exactos o contengan errores.</p>
            <p></p>
            <p>11- Revocación de la compra. Para las compras realizadas por medio de éste Sitio, los Clientes dispondrán de un plazo de hasta de diez (10) días corridos para revocarlas. A esos efectos, los Clientes deberán comunicar su decisión a LilianaGameStore.com por escrito o medios electrónicos o similares, o mediante la devolución de los productos adquiridos. Dicho plazo será computado a partir de la entrega de los productos y de vencer en día inhábil, este se entenderá prorrogado hasta el primer día hábil inmediato siguiente. Pasado ese plazo, no habrá de obstar para que LilianaGameStore.com busque la mejor solución posible en pos de lograr la satisfacción de los Usuarios. El ejercicio del derecho de revocación no habrá de implicar gasto alguno para quiénes así lo decidan. Siendo ejercido el derecho de revocar en tiempo y forma, las partes quedarán liberadas de sus obligaciones respectivas, debiendo restituirse recíproca y simultáneamente las prestaciones que han cumplido. La imposibilidad de devolver los productos adquiridos no privará a los Clientes de sus respectivos derechos. Si la imposibilidad les fuera imputables, deberán pagar el valor de mercado que los productos que hayan adquirido tengan al momento del ejercicio del derecho a revocar, excepto que dicho valor sea superior al precio de adquisición, en cuyo caso la obligación quedará limitada a este último.</p>
            <p></p>
            <p>12- Comprar en LilianaGameStore.com es SEGURO. Los datos ingresados de las tarjetas de crédito no son almacenados en las bases de datos de LilianaGameStore.com, siendo enviados directamente a la plataforma aprobada por las correspondientes entidades administradoras de las mismas.</p>
            <p></p>
            <p>13- Cambios de productos. Para productos comprados en LilianaGameStore.com, el cambio se puede realizar dentro de los 10 días corridos contados a partir de la entrega del producto.</p>
            <p></p>
            <p>Para productos comprados en las sucursales, el cambio puede realizarse dentro de las 72hs contando desde la entrega, siempre y cuando el producto no haya sido instalado. Si el producto fue instalado, debe ser revisado por el técnico oficial de la marca, el cual informará los pasos a seguir.</p>
            <p></p>
            <p>Los cambios de CD y DVD pueden realizarse dentro de los 15 días corridos contados a partir de la entrega. El producto debe tener la faja o el envoltorio original y en buenas condiciones.</p>
            <p></p>
            <p>Para realizar el cambio, el producto debe estar en perfecto estado de uso, completo, con embalaje original, factura de compra o ticket de regalo. Una vez recibido el producto, se verificará y solo si cumple con los requisitos se procederá al cambio.</p>
            <p></p>
            <p>Para tramitar los cambios de producto, es necesario contactarse al Servicio de Atención al Cliente, donde un asesor le informará los pasos a seguir. El usuario puede enviar un email a contacto@lilianagamestore.com o llamar al 0800-345-9331 de lunes a sábado de 8:30 a 20:30hs.</p>
            <p></p>
            <p>14- Garantía de buen funcionamiento. Los Clientes gozarán de garantía legal por los defectos o vicios de cualquier índole, que puedan verificarse en los productos que adquieran, aunque éstos hayan sido ostensibles o manifiestos al tiempo de la compra, siempre que afecten la identidad entre lo ofrecido y lo entregado, o su correcto funcionamiento. La vigencia de la garantía comienza a regir a partir de la entrega y dependerá de cada marca de producto. En el caso de que el producto presente una falla de funcionamiento durante el período legal, el cliente deberá comunicarse con el canal de contacto expreso en el manual del bien adquirido para que le proporcionen los pasos a seguir a fin de acceder a la garantía del producto. El cliente deberá custodiar el embalaje original del producto. En caso que los productos deban trasladarse a fábrica o taller habilitado el transporte será realizado por el responsable de la garantía, a cuyo cargo estarán los gastos de flete y seguros y cualquier otro que deba realizarse para la ejecución del mismo. El tiempo durante el cual los clientes se vean privados del uso del objeto en garantía, por cualquier causa relacionada con su reparación, habrá de computarse como prolongación del plazo de garantía legal.</p>
            <p></p>
            <p>15- Información sobre el Sitio LilianaGameStore.com con el propósito de que los Usuarios puedan comprender los riesgos derivados del empleo del Sitio, y para que tengan absolutamente claro los posibles riesgos, Liliana GameStore informa que en tanto el universo de riesgo puede cambiar tan drásticamente en cuestión de minutos que no es humanamente posible planificar cualquier eventualidad, no puede garantizar  a los Usuarios el acceso y uso continuado o ininterrumpido de su Sitio. El sistema puede eventualmente no estar disponible, debido a dificultades técnicas o fallas de Internet, o por cualquier otra circunstancia ajena a su voluntad; un error o fallo del sistema eventualmente pude desencadenar un resultado indeseado. Los Usuarios no podrán acceder ni intentar acceder al Sitio ni usar ninguno de los servicios por ningún otro medio que no sea la interfaz provista por LilianaGameStore.com. Está prohibido a los Usuarios violar, vulnerar y/o de cualquier forma afectar el normal uso y la seguridad del Sitio, utilizar cualquier dispositivo, software o rutina para interferir o intentar interferir con el buen funcionamiento del Sitio o cualquier actividad que se lleve a cabo en este Sitio. Cualquier hecho, acto u omisión vinculados con lo referido anteriormente y que tengan aptitud para afectar la seguridad y/o el normal desarrollo del Sitio tienen entidad suficiente para causar a LilianaGameStore.com considerables daños y perjuicios incluyendo pero no limitándose a lucro cesante por caída y/o merma en las ventas, afectación de sus marcas, imagen comercial, pérdida de clientela, etc. El acceso a este Sitio no autoriza a nadie a utilizar cualquier nombre, logotipo o marca de cualquier manera. No se concede ninguna licencia de marca registrada o marca de servicio en relación con los materiales contenidos en este Sitio Los nombres y logotipos del Sitio y todos los productos relacionados, y nombres de servicio, marcas de diseño y eslóganes son propiedad de sus respectivos registrantes.</p>
            <p></p>
            <p>16- Legislación aplicable</p>
            <p></p>
            <p>El presente es regido por las leyes de la República Argentina.</p>
          </div>
          <div className="modal-footer">
            <button type="button" className="btn btn-outline-danger" data-bs-dismiss="modal">Cerrar</button>
            <button type="button" className="btn btn-outline-info" data-bs-dismiss="modal" onClick={handleAccept}>Aceptar</button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Terms;